### ISSUE TITLE
IsTemplateLiteral, IsStringLiteral, etc is not working correctly in TS 5.1+

### ISSUE THREAD

**Issue by unional** [cyberuni/type-plus#429]
```sh
type-plus:build: src/mix_types/merge.spec.ts(71,6): error TS2345: Argument of type 'boolean' is not assignable to parameter of type 'never'.
type-plus:build: src/string/is_not_string_literal.spec.ts(305,77): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_not_string_literal.spec.ts(306,98): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_not_template_literal.spec.ts(102,64): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_not_template_literal.spec.ts(106,71): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_not_template_literal.spec.ts(194,90): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_not_template_literal.spec.ts(198,97): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_string_literal.spec.ts(632,73): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_string_literal.spec.ts(740,95): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_template_literal.spec.ts(213,62): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_template_literal.spec.ts(215,58): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_template_literal.spec.ts(216,61): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_template_literal.spec.ts(219,67): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_template_literal.spec.ts(225,69): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_template_literal.spec.ts(228,69): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_template_literal.spec.ts(412,88): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_template_literal.spec.ts(414,84): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_template_literal.spec.ts(415,87): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_template_literal.spec.ts(418,93): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_template_literal.spec.ts(424,95): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
type-plus:build: src/string/is_template_literal.spec.ts(427,95): error TS2345: Argument of type 'true' is not assignable to parameter of type 'false'.
```
